MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes

src/gadgets/ReferenceTooltips/MediaWiki:Gadget-ReferenceTooltips.js
Spread syntax throws an error with undefined.
=> fix(ReferenceTooltips.js): fix spread syntax

src/gadgets/mobile-styles/MediaWiki:Gadget-mobile-styles.css
On a small screen, ol numbers will be partly invisible. See [this special page](https://mzh.moegirl.org.cn/Special:%E7%9F%AD%E9%A1%B5%E9%9D%A2) as an example.
The padding of 2.25em is used in [MinervaNeue](https://github.com/wikimedia/mediawiki-skins-MinervaNeue/blob/1a2960a3c0129f3cd3e9754802c4272d240862e5/resources/skins.minerva.base.styles/content/lists.less#L3).
=> fix(Gadget-mobile-styles.css): ol on small screens

src/gadgets/mobile-styles/MediaWiki:Gadget-mobile-styles.css
My previous pull request (#49) did not consider the `margin-left-set` class added by [gadget-site-js.js](/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/blob/master/src/gadgets/site-js/MediaWiki:Gadget-site-js.js#L337). This commit will fix the conflict by ignoring those ordered lists with a nonzero margin-left.
=> fix(mobile-styles): conflict with margin-left-set

src/global/MediaWiki:Moeskin.js
解决[Moeskin.js](/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/blob/master/src/global/MediaWiki:Moeskin.js#L79)与[Gadget-site-lib.js](/MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes/blob/master/src/gadgets/site-lib/MediaWiki:Gadget-site-lib.js#L29)间的冲突。
=> fix(Moeskin.js): configurable addPortletLink

src/gadgets/moeskin-styles/MediaWiki:Gadget-moeskin-styles.css
Buttons of an `OO.ui.ProcessDialog` should not be hidden below `#moe-global-header`.
=> fix(moeskin-styles): OO.ui.Dialog z-index

src/gadgets/UserMessages/definition.json
近期该小工具无法正常调用jquery.ui，代码太长难以统计用了多少组件，直接调用整库
=> add jQuery UI dependency

src/global/MediaWiki:Moeskin.js
[讨论版](https://zh.moegirl.org.cn/萌娘百科_talk:讨论版/技术实现#萌皮图像显示形式有差异)上提到的关于`<gallery mode="slideshow">`的bug严重妨碍了条目的正常阅读，但遗憾的是迟迟未得到运营的回应。因此尝试通过站内JS临时修复，并顺便修复讨论版上新提出的[关于MultiMediaViewer的bug](https://zh.moegirl.org.cn/萌娘百科_talk:讨论版/技术实现#MoeSkin查看大图的问题)。
=> fix(Moeskin.js): fix a few image issues

scripts/prefetch/targets.js
连续几天GitHub Actions都无法正常从unpkg.com下载脚本，所以请求重新改回jsdelivr。
revert 61541c4203f17684c6dcdbd55c4fe5acef252c1b
=> revert(target.js): switch back to jsdelivr

src/global/MediaWiki:Moeskin.js
不是致命错误，但每次控制台都会报错也挺难受的。万一以后哪天同时有一个真bug发生可能会造成debug时的困扰。另外如果不介意让所有启用媒体查看器的用户（包括所有匿名用户）都在每个页面加载一次`mmv.bootstrap.autostart`模块的话，第74行可以不改。
=> fix(Moeskin.js): fix MultiMediaViewer module name

src/gadgets/wikieditor-highlight/MediaWiki:Gadget-wikieditor-highlight.js
移除对不再使用的Minerva皮肤的支持，并不再区分受保护的页面。
=> fix(wikieditor-highlight): fix font-size

src/gadgets/site-styles/MediaWiki:Gadget-site-styles.css
信息栏2.0后面的{{tabs}}使用AutoWidth=yes会清除浮动（Special:固定链接/6690073），不用则会出现多余白底盖住信息栏。此法解决前后效果差见Special:diff/6690115。
=> 修复和信息栏2.0的兼容问题

src/gadgets/patrolPlus/definition.json
=> feat: available on moeskin

.mailmap, src/gadgets/wikiBlame/MediaWiki:Gadget-wikiBlame.js
使用`action=query`且`prop=revisions`获取条目的历史版本时顺便获取wikitext以减少对服务器的负担。
例如，如果条目有100个版本，其中有2个添加了指定的文字，原本的做法是提交1个请求获取`revisions`，再提交100次`compare`请求。
更新后会先提交100/50=2个请求获取所有历史版本及其源代码，再判断哪些版本的源代码添加了指定的文字，最后再使用`compare`对比找到的2个版本。
这个算法的问题在于如果指定文字多次出现（例如，从出现1次到出现2次），则不会触发程序的判断，尽管mw自带的`compare`可以发现。但是和性能的大幅提高比起来，这个问题可以忽略。
=> feat(wikiBlame): use more efficient api to reduce server load

.mailmap, src/gadgets/site-styles/MediaWiki:Gadget-site-styles.css
The shared file description feature has been disabled from the server side, so this rule is unused.
I think it should be enabled though, since nowadays file descriptions are generally proper enough.
=> site-styles: Remove the unused rule about file description

src/gadgets/SideBarPic/MediaWiki:Gadget-SideBarPic.css
- Removed the unnecessary `div` prefix to class and id selectors. Here we do not need to improve specificity nor have unexpected matches.
- Removed commented-out codes.
=> chore: Clean up CSS of the SideBarPic gadget

src/gadgets/wikieditor-highlight-cm6/MediaWiki:Gadget-wikieditor-highlight-cm6.js, src/gadgets/wikieditor-highlight-cm6/definition.yaml
Update MediaWiki:Gadget-wikieditor-highlight.js using CodeMirror 6
Beta version for techedit
=> feat: Gadget-wikieditor-highlight-cm6

src/gadgets/wikieditor-highlight-cm6/MediaWiki:Gadget-wikieditor-highlight-cm6.js
- 对Widget模式进行了一些更新
- 忽略一些扩展标签相关的false positive的语法错误
=> fix(wikieditor-highlight-cm6): avoid reusing global CodeMirror

src/gadgets/wikieditor-highlight/MediaWiki:Gadget-wikieditor-highlight.js
Borrowed from MW:Extension:CodeMirror
=> fix(MediaWiki:Gadget-wikieditor-highlight.js): missing style

src/gadgets/wikieditor-highlight/MediaWiki:Gadget-wikieditor-highlight.css, src/gadgets/wikieditor-highlight/MediaWiki:Gadget-wikieditor-highlight.js, src/gadgets/wikieditor-highlight/definition.yaml
=> fix(wikieditor-highlight): 适配MoeSkin

src/gadgets/wikieditor-highlight/MediaWiki:Gadget-wikieditor-highlight.js
=> feat(Gadget-wikieditor-highlight.js): multiple selections

src/gadgets/SideBarPic/MediaWiki:Gadget-SideBarPic.css
此两 CSS 已经由 MoeSkin 本身修复，不再需要且会导致 dark 模式颜色错误
=> fix(Gadget/SideBarPic): :bug: 修复dark模式颜色错误

src/gadgets/flagEditWar/MediaWiki:Gadget-flagEditWar.js
temporary fix (in fact in this use case it's unnecessary?)
Fix #537
=> fix(Gadget/flagEditWar): bug fix

src/gadgets/moeskin-styles/MediaWiki:Gadget-moeskin-styles.css
不记得了就先删了吧，MSP 最近几天试下来也没发现问题
Close #555
=> fix(Gadget/moeskin-styles): :bug: 萌皮移动版下class=navbox的表格显示错位
