MoegirlPediaInterfaceAdmins/MoegirlPediaInterfaceCodes

src/gadgets/libOOUIDialog/MediaWiki:Gadget-libOOUIDialog.js
=> feat(Gadget-libOOUIDialog): Force `required`

src/gadgets/moeskin-styles/MediaWiki:Gadget-moeskin-styles.css
=> fix: bold text in the MoeSkin

src/gadgets/CommentsinLocalTime/MediaWiki:Gadget-CommentsinLocalTime.js
English letters will be formatted again by moment.js
=> fix(CommentsInLocalTime): don't format twice

src/gadgets/moeskin-styles/MediaWiki:Gadget-moeskin-styles.css
change pagetools and notice id
=> moeskin 2.0

src/gadgets/ReferenceTooltips/MediaWiki:Gadget-ReferenceTooltips.js, src/gadgets/autoconfirmedUserPing/MediaWiki:Gadget-autoconfirmedUserPing.js, src/gadgets/interfaceVariantConverter/MediaWiki:Gadget-interfaceVariantConverter.js, src/gadgets/moveToUserSubpage/MediaWiki:Gadget-moveToUserSubpage.js, src/gadgets/quickMoveThread/MediaWiki:Gadget-quickMoveThread.js, src/gadgets/registerToDelete/MediaWiki:Gadget-registerToDelete.js, src/gadgets/report/MediaWiki:Gadget-report.js
Please let me know if z-index 100 is necessary.
=> fix(gadget-report): fix tagName and z-index

src/gadgets/ShowAvatar/MediaWiki:Gadget-ShowAvatar.css, src/gadgets/ShowAvatar/MediaWiki:Gadget-ShowAvatar.js
1.补充vector皮肤上传头像链接标题 2.调整moeskin下用户根页面头像排版 3.补上星海漏掉的斜杠
=> fix: showavatar styles and upload title

src/gadgets/Navigation_popups/MediaWiki:Gadget-popups.js, src/gadgets/noteTA/MediaWiki:Gadget-noteTA.js
This mistake prevents the image preview.
=> fix(popups.js): no-use-before-define

src/gadgets/moeskin-styles/MediaWiki:Gadget-moeskin-styles.css, src/gadgets/site-js/MediaWiki:Gadget-site-js.js
=> feat: + 2023NewYear background & SP activity

src/gadgets/MarkAsResolved/MediaWiki:Gadget-MarkAsResolved.css
=> feat: responsive size

src/gadgets/Wikiplus/MediaWiki:Gadget-Wikiplus.css
=> 调整萌皮窄屏下快速编辑按钮样式

.mailmap, src/gadgets/Wikiplus/MediaWiki:Gadget-Wikiplus.css
=> 修正错误的Breakpoint

src/gadgets/site-styles/MediaWiki:Gadget-site-styles.css
Special:固定链接/6761157#请求实现黑幕能盖住彩色表情
=> 黑幕中图片的样式支持

src/gadgets/shortlink/MediaWiki:Gadget-shortlink.js, src/gadgets/shortlink/definition.yaml
RT，萌皮上效果如下，会添加在自定义工具栏下方（没有自定义工具栏的话就是公告下方）
vector理论上效果不变
=> feat: 适配萌皮

src/gadgets/site-styles/MediaWiki:Gadget-site-styles.css
=> 提出{{胡话}}的内联CSS

src/gadgets/interfaceVariantConverter/definition.yaml, src/gadgets/libCachedCode/definition.yaml, src/gadgets/queryContributions/definition.yaml, src/gadgets/site-lib/definition.yaml
=> fix: libCachedCode dependency in commons

src/gadgets/moeskin-styles/MediaWiki:Gadget-moeskin-styles.css
=> revert: banner image

src/gadgets/MarkAsResolved-restricted/MediaWiki:Gadget-MarkAsResolved-restricted.js, src/gadgets/MarkAsResolved/MediaWiki:Gadget-MarkAsResolved.js
=> fix(MarkAsResolved): allow reselection of status on error

src/gadgets/MarkAsResolved-restricted/MediaWiki:Gadget-MarkAsResolved-restricted.js, src/gadgets/MarkAsResolved/MediaWiki:Gadget-MarkAsResolved.js, src/gadgets/Navbox-link/MediaWiki:Gadget-Navbox-link.js, src/gadgets/Purgecache/MediaWiki:Gadget-Purgecache.js, src/gadgets/SendWelcomeMessage/MediaWiki:Gadget-SendWelcomeMessage.js, src/gadgets/SpecialWikitext/MediaWiki:Gadget-SpecialWikitext.js, src/gadgets/UserMessages/MediaWiki:Gadget-UserMessages.js, src/gadgets/abusefilter33test/MediaWiki:Gadget-abusefilter33test.js, src/gadgets/abusefilterEdit/MediaWiki:Gadget-abusefilteredit.js, src/gadgets/allmessageFilter/MediaWiki:Gadget-allmessageFilter.js, src/gadgets/autoconfirmedUserPing/MediaWiki:Gadget-autoconfirmedUserPing.js, src/gadgets/backlog/MediaWiki:Gadget-backlog.js, src/gadgets/blockEnhance/MediaWiki:Gadget-blockEnhance.js, src/gadgets/deletion/MediaWiki:Gadget-deletion.js, src/gadgets/flagBlocked/MediaWiki:Gadget-flagBlocked.js, src/gadgets/flagEditWar/MediaWiki:Gadget-flagEditWar.js, src/gadgets/interfaceVariantConverter/MediaWiki:Gadget-interfaceVariantConverter.js, src/gadgets/moveToUserSubpage/MediaWiki:Gadget-moveToUserSubpage.js, src/gadgets/noteTA/MediaWiki:Gadget-noteTA.js, src/gadgets/patrolPlus/MediaWiki:Gadget-patrolPlus.js, src/gadgets/queryContributions/MediaWiki:Gadget-queryContributions.js, src/gadgets/queryWhatlinkshere/MediaWiki:Gadget-queryWhatlinkshere.js, src/gadgets/quickMoveThread/MediaWiki:Gadget-quickMoveThread.js, src/gadgets/quickSave/MediaWiki:Gadget-quickSave.js, src/gadgets/registerToDelete/MediaWiki:Gadget-registerToDelete.js, src/gadgets/report/MediaWiki:Gadget-report.js, src/gadgets/rollback-summary/MediaWiki:Gadget-rollback-summary.js, src/gadgets/temp-editcheck/MediaWiki:Gadget-temp-editcheck.js, src/gadgets/userpageDelete/MediaWiki:Gadget-userpageDelete.js, src/gadgets/wikiBlame/MediaWiki:Gadget-wikiBlame.js
API请求管理：为所有登录用户才可使用的小工具的API请求加上用户名验证
=> feat: assertuser

src/gadgets/wikieditor-highlight-cm6/MediaWiki:Gadget-wikieditor-highlight-cm6.js, src/gadgets/wikieditor-highlight-cm6/definition.yaml
1. assuming templates to be transcluded
2. loading full parser config
=> [PLEASE SQUASH]fix(wikieditor-highlight-cm6): fix wikilint

src/gadgets/wikieditor-highlight/MediaWiki:Gadget-wikieditor-highlight.js
=> fix(MediaWiki:Gadget-wikieditor-highlight.js): toggle

src/gadgets/quickMoveThread/MediaWiki:Gadget-quickMoveThread.js, src/gadgets/registerToDelete/MediaWiki:Gadget-registerToDelete.js
不确定有没有更好的办法。
如果知道OOUI下拉菜单的上级class，可以再用setTimeout加个自定义class，然后用CSS实现
=> feat: Make dropdownToggle animated

src/gadgets/uploader/MediaWiki:Gadget-uploader.js
现在直接mw.util.addPortletLink就行了吧
=> fix(Gadget/uploader): :bug: 没有MOE_SKIN_GLOBAL_DATA_REF了

src/gadgets/usergroup/MediaWiki:Gadget-usergroup.js
=。=
https://mzh.moegirl.org.cn/_?oldid=7411118
=> fix(Gadget/usergroup): :bug: 恢复缺少的[封+]

src/gadgets/moveToUserSubpage/MediaWiki:Gadget-moveToUserSubpage.js
=> feat: 打回工具支持审核扩展

src/global/zh/MediaWiki:WikiLove.js
=> feat: 添加特色星章
